controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    antenna_controller:
      type: joint_trajectory_controller/JointTrajectoryController

antenna_controller:
  ros__parameters:
    joints:
      - antenna_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
